import { PERMISSIONS, PermissionKey } from './permission.constants';

const allPermissions = Object.values(PERMISSIONS);

export const PERMISSION_MATRIX: Record<string, PermissionKey[]> = {
  PLATFORM_ADMIN: allPermissions,
  TENANT_ADMIN: allPermissions.filter((item) => item !== PERMISSIONS.BILLING_MANAGE || true),
  FARM_MANAGER: [
    PERMISSIONS.MOBILE_READ,
    PERMISSIONS.DEVICE_READ,
    PERMISSIONS.DEVICE_MANAGE,
    PERMISSIONS.IRRIGATION_READ,
    PERMISSIONS.IRRIGATION_EXECUTE,
    PERMISSIONS.FERTIGATION_EXECUTE,
    PERMISSIONS.DRONE_READ,
    PERMISSIONS.DRONE_REVIEW,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.COST_READ,
    PERMISSIONS.AI_READ,
    PERMISSIONS.APPROVAL_APPROVE,
    PERMISSIONS.ACTION_EXECUTE,
    PERMISSIONS.ACTION_CANCEL,
    PERMISSIONS.SAFETY_MANAGE
  ],
  OPERATOR: [
    PERMISSIONS.MOBILE_READ,
    PERMISSIONS.DEVICE_READ,
    PERMISSIONS.IRRIGATION_READ,
    PERMISSIONS.DRONE_READ,
    PERMISSIONS.REPORT_READ,
    PERMISSIONS.AI_READ,
    PERMISSIONS.ACTION_EXECUTE
  ],
  VIEWER: [PERMISSIONS.MOBILE_READ, PERMISSIONS.DEVICE_READ, PERMISSIONS.IRRIGATION_READ, PERMISSIONS.DRONE_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.AI_READ],
  INSTALLER: [PERMISSIONS.DEVICE_READ, PERMISSIONS.INSTALLER_CHECK, PERMISSIONS.BLUETOOTH_MAINTAIN, PERMISSIONS.EDGE_MANAGE],
  MAINTAINER: [PERMISSIONS.DEVICE_READ, PERMISSIONS.DEVICE_MANAGE, PERMISSIONS.INSTALLER_CHECK, PERMISSIONS.BLUETOOTH_MAINTAIN, PERMISSIONS.EDGE_MANAGE, PERMISSIONS.EMERGENCY_STOP],
  FARMER: [PERMISSIONS.MOBILE_READ, PERMISSIONS.DEVICE_READ, PERMISSIONS.IRRIGATION_READ, PERMISSIONS.DRONE_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.AI_READ],
  LARGE_GROWER: [PERMISSIONS.MOBILE_READ, PERMISSIONS.DEVICE_READ, PERMISSIONS.IRRIGATION_READ, PERMISSIONS.DRONE_READ, PERMISSIONS.REPORT_READ, PERMISSIONS.COST_READ, PERMISSIONS.AI_READ],
  COOPERATIVE_ADMIN: allPermissions,
  DRONE_PILOT: [PERMISSIONS.DRONE_READ, PERMISSIONS.DRONE_REVIEW, PERMISSIONS.REPORT_READ],
  MACHINERY_PROVIDER: [PERMISSIONS.MOBILE_READ, PERMISSIONS.REPORT_READ],
  INPUT_STORE: [PERMISSIONS.MOBILE_READ]
};

export function hasPermissions(role: string | undefined, required: PermissionKey[]) {
  if (!required.length) return true;
  const granted = role ? PERMISSION_MATRIX[role] ?? [] : [];
  return required.every((permission) => granted.includes(permission));
}
