ALTER TABLE `FarmActivity` MODIFY `type` ENUM('SENSOR_ALERT', 'IRRIGATION_STARTED', 'IRRIGATION_COMPLETED', 'FERTIGATION_STARTED', 'FERTIGATION_COMPLETED', 'ROTATION_STARTED', 'ROTATION_COMPLETED', 'DRONE_OPERATION_IMPORTED', 'DRONE_OPERATION_REVIEWED', 'DRONE_SPRAYING_COMPLETED', 'DRONE_MAPPING_COMPLETED', 'DEVICE_OFFLINE', 'DEVICE_RECOVERED', 'AI_DECISION_CREATED', 'MANUAL_OPERATION') NOT NULL;

CREATE TABLE `OperationCost` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NULL,
  `farmId` VARCHAR(191) NOT NULL,
  `fieldId` VARCHAR(191) NULL,
  `refType` VARCHAR(191) NOT NULL,
  `refId` VARCHAR(191) NOT NULL,
  `category` ENUM('PESTICIDE', 'FERTILIZER', 'WATER', 'ELECTRICITY', 'LABOR', 'DRONE_SERVICE', 'MACHINE', 'OTHER') NOT NULL,
  `amount` DOUBLE NOT NULL DEFAULT 0,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'CNY',
  `quantity` DOUBLE NULL,
  `unit` VARCHAR(191) NULL,
  `unitPrice` DOUBLE NULL,
  `note` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `OperationCost_tenantId_idx`(`tenantId`),
  INDEX `OperationCost_farmId_idx`(`farmId`),
  INDEX `OperationCost_fieldId_idx`(`fieldId`),
  INDEX `OperationCost_refType_refId_idx`(`refType`, `refId`),
  INDEX `OperationCost_category_idx`(`category`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `DroneOperationReview` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NULL,
  `farmId` VARCHAR(191) NOT NULL,
  `droneOperationId` VARCHAR(191) NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_MANUAL_LINK', 'NEEDS_BOUNDARY_FIX') NOT NULL DEFAULT 'PENDING',
  `reviewerId` VARCHAR(191) NULL,
  `reviewNote` TEXT NULL,
  `correctedFieldId` VARCHAR(191) NULL,
  `correctedFieldBoundaryId` VARCHAR(191) NULL,
  `correctedCoverageGeoJson` JSON NULL,
  `correctedRouteGeoJson` JSON NULL,
  `confirmedAreaMu` DOUBLE NULL,
  `confirmedCoverageRate` DOUBLE NULL,
  `confirmedMissedAreaMu` DOUBLE NULL,
  `confirmedRepeatedAreaMu` DOUBLE NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `reviewedAt` DATETIME(3) NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  INDEX `DroneOperationReview_tenantId_idx`(`tenantId`),
  INDEX `DroneOperationReview_farmId_idx`(`farmId`),
  INDEX `DroneOperationReview_droneOperationId_idx`(`droneOperationId`),
  INDEX `DroneOperationReview_status_idx`(`status`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CropHealthObservation` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NULL,
  `farmId` VARCHAR(191) NOT NULL,
  `fieldId` VARCHAR(191) NULL,
  `droneOperationId` VARCHAR(191) NULL,
  `source` ENUM('DRONE_SCOUTING', 'MANUAL', 'SENSOR', 'AI_RECOGNITION') NOT NULL,
  `type` ENUM('PEST', 'DISEASE', 'WEED', 'WATER_STRESS', 'NUTRIENT_STRESS', 'UNKNOWN') NOT NULL,
  `severity` VARCHAR(191) NULL,
  `title` VARCHAR(191) NOT NULL,
  `description` TEXT NULL,
  `locationGeoJson` JSON NULL,
  `imageUrls` JSON NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `CropHealthObservation_tenantId_idx`(`tenantId`),
  INDEX `CropHealthObservation_farmId_idx`(`farmId`),
  INDEX `CropHealthObservation_fieldId_idx`(`fieldId`),
  INDEX `CropHealthObservation_droneOperationId_idx`(`droneOperationId`),
  INDEX `CropHealthObservation_source_idx`(`source`),
  INDEX `CropHealthObservation_type_idx`(`type`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `YieldRecord` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NULL,
  `farmId` VARCHAR(191) NOT NULL,
  `fieldId` VARCHAR(191) NOT NULL,
  `cropType` VARCHAR(191) NULL,
  `cropSeason` VARCHAR(191) NULL,
  `yieldKg` DOUBLE NULL,
  `areaMu` DOUBLE NULL,
  `yieldPerMu` DOUBLE NULL,
  `source` VARCHAR(191) NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `YieldRecord_tenantId_idx`(`tenantId`),
  INDEX `YieldRecord_farmId_idx`(`farmId`),
  INDEX `YieldRecord_fieldId_idx`(`fieldId`),
  INDEX `YieldRecord_cropSeason_idx`(`cropSeason`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `YieldFactor` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NULL,
  `farmId` VARCHAR(191) NOT NULL,
  `fieldId` VARCHAR(191) NOT NULL,
  `cropSeason` VARCHAR(191) NULL,
  `factorType` ENUM('IRRIGATION', 'FERTIGATION', 'DRONE_SPRAYING', 'DRONE_SCOUTING', 'PEST_DISEASE', 'WEATHER', 'SOIL_MOISTURE', 'MANUAL_NOTE') NOT NULL,
  `refType` VARCHAR(191) NULL,
  `refId` VARCHAR(191) NULL,
  `valueJson` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `YieldFactor_tenantId_idx`(`tenantId`),
  INDEX `YieldFactor_farmId_idx`(`farmId`),
  INDEX `YieldFactor_fieldId_idx`(`fieldId`),
  INDEX `YieldFactor_cropSeason_idx`(`cropSeason`),
  INDEX `YieldFactor_factorType_idx`(`factorType`),
  INDEX `YieldFactor_refType_refId_idx`(`refType`, `refId`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
