import 'reflect-metadata';
import assert = require('node:assert/strict');
import { BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { activeEmergencyIdentity, ControlCommandArbiter, EdgeReliabilityAgent, PriorityCommandSerializer } from '@agrios/edge-core';
import { RequestContextService } from '../src/common/request-context.service';
import { DeviceControlService } from '../src/modules/device-control/device-control.service';
import { PlcGatewayDeviceController } from '../src/modules/device-control/adapters/plc-gateway-device-controller';
import { SafetyService } from '../src/modules/safety/safety.service';
import { ActionExecutorService } from '../src/modules/decision-engine/action-executor.service';

type Test = { name: string; run: () => void | Promise<void> }; const tests: Test[] = []; const test = (name: string, run: Test['run']) => tests.push({ name, run });
const scope = { edgeId: 'edge-a', tenantId: 'tenant-a', farmId: 'farm-a', deviceId: 'plc-a' };
const future = () => new Date(Date.now() + 60_000).toISOString();
const agent = () => new EdgeReliabilityAgent({ command: () => undefined } as any, {} as any, { edgeId: scope.edgeId, tenantId: scope.tenantId, farmId: scope.farmId, deviceIds: [scope.deviceId] });
const envelope = (overrides: Record<string, unknown> = {}) => ({ commandId: 'cmd-1', ...scope, action: 'EMERGENCY_STOP', expiresAt: future(), signatureValid: true, ...overrides } as any);

test('invalid HMAC E-stop does not latch or increment generation', () => { const a = new ControlCommandArbiter(); const before = a.currentGeneration(); assert.throws(() => agent().validateCommand(envelope({ signatureValid: false }))); assert.equal(a.isEmergencyLatched(), false); assert.equal(a.currentGeneration(), before); });
test('invalid HMAC reset does not clear active latch', () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('estop-1'); const before = a.currentGeneration(); assert.throws(() => agent().validateCommand(envelope({ action: 'RESET_EMERGENCY_STOP', signatureValid: false, resetOfCommandId: 'estop-1' }))); assert.equal(a.activeEmergencyId(), 'estop-1'); assert.equal(a.currentGeneration(), before); });
for (const [name, value] of [['edgeId', 'wrong-edge'], ['tenantId', 'wrong-tenant'], ['farmId', 'wrong-farm'], ['deviceId', 'wrong-device']] as const) test(`wrong ${name} reset cannot clear latch`, () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('estop-1'); assert.throws(() => agent().validateCommand(envelope({ action: 'RESET_EMERGENCY_STOP', resetOfCommandId: 'estop-1', [name]: value }))); assert.equal(a.activeEmergencyId(), 'estop-1'); });
test('duplicate old reset cannot clear newer E-stop', async () => { const a = new ControlCommandArbiter(); await a.submit({ action: 'EMERGENCY_STOP', commandId: 'e1' }, async () => true); await a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'r1', resetOfCommandId: 'e1' }, async () => true); await a.submit({ action: 'EMERGENCY_STOP', commandId: 'e2' }, async () => true); await assert.rejects(() => a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'r1-replay', resetOfCommandId: 'e1' }, async () => true)); assert.equal(a.activeEmergencyId(), 'e2'); });
test('expired reset is rejected before arbiter mutation', () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('e2'); assert.throws(() => agent().validateCommand(envelope({ action: 'RESET_EMERGENCY_STOP', resetOfCommandId: 'e2', expiresAt: new Date(Date.now() - 1).toISOString() }))); assert.equal(a.activeEmergencyId(), 'e2'); });
test('restart restores active latch identity', () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('persisted-e2'); assert.equal(a.activeEmergencyId(), 'persisted-e2'); });
test('restart ignores duplicate E-stop identity records', () => { assert.equal(activeEmergencyIdentity([{ action: 'EMERGENCY_STOP', commandId: 'e1', result: { status: 'SUCCEEDED' } }, { action: 'EMERGENCY_STOP', commandId: 'duplicate', result: { status: 'ALREADY_LATCHED' } }]), 'e1'); });
test('restart plus stale reset remains blocked', async () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('persisted-e2'); await assert.rejects(() => a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'old-reset', resetOfCommandId: 'e1' }, async () => true)); assert.equal(a.activeEmergencyId(), 'persisted-e2'); });
test('valid current reset clears latch', async () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('e2'); await a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'r2', resetOfCommandId: 'e2' }, async () => true); assert.equal(a.isEmergencyLatched(), false); });
test('reset does not auto-run old START', async () => { const a = new ControlCommandArbiter(); let unsafe = 0; const start = a.submit({ action: 'PUMP_ON', commandId: 'start-old' }, async (allowed) => { if (allowed) unsafe++; return allowed; }); await a.submit({ action: 'EMERGENCY_STOP', commandId: 'e1' }, async () => true); await a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'r1', resetOfCommandId: 'e1' }, async () => true); await start; assert.equal(unsafe, 0); });
test('dangerous START remains blocked after invalid reset', async () => { const a = new ControlCommandArbiter(); a.restoreEmergencyLatch('e2'); await assert.rejects(() => a.submit({ action: 'RESET_EMERGENCY_STOP', commandId: 'bad', resetOfCommandId: 'e1' }, async () => true)); let unsafe = 0; await a.submit('VALVE_OPEN', async (allowed) => { if (allowed) unsafe++; return allowed; }); assert.equal(unsafe, 0); });

function productionFixture() {
  const values: Record<string, any> = { NODE_ENV: 'test', PLC_GATEWAY_FAKE_TRANSPORT: 'true', DEVICE_CONTROL_MODE: 'PLC_GATEWAY', DEVICE_CONTROL_DRY_RUN: 'false', VALVE_ALLOW_REAL_CONTROL: 'true', ENABLE_AUTO_EXECUTION: 'true', PLC_TRANSPORT: 'FAKE', PLC_REAL_WRITE_ENABLED: 'false', PLC_PROFILE: { unitId: 1, points: { pumpStop: { type: 'coil', address: 1 }, pumpStart: { type: 'coil', address: 2 }, valveClose: { type: 'coil', address: 3 }, valveOpen: { type: 'coil', address: 4 } } } };
  const config = { get: (key: string) => values[key] } as ConfigService; const plc = new PlcGatewayDeviceController(config); Object.assign((plc as any).status, { online: true, valveOpen: true, pumpRunning: true });
  const ctx = new RequestContextService(); const eventLogs: any[] = [];
  const deviceControl = new DeviceControlService(plc as any, plc as any, plc as any, plc as any, plc, plc as any, { publish: () => undefined } as any, config, { eventLog: { create: async (x: any) => { eventLogs.push(x); return x; } } } as any, ctx, { record: async () => ({}) } as any);
  return { config, plc, ctx, deviceControl, eventLogs };
}
const payload = (overrides: Record<string, unknown> = {}) => { const requestedAt = new Date(); return { tenantId: 'tenant-a', farmId: 'farm-a', fieldId: 'field-a', deviceId: 'plc-a', commandId: 'safety-1', idempotencyKey: 'safety-1', requestedAt: requestedAt.toISOString(), expiresAt: new Date(requestedAt.getTime() + 30_000).toISOString(), ...overrides }; };
const inContext = <T>(ctx: RequestContextService, callback: () => T | Promise<T>) => new Promise<T>((resolve, reject) => ctx.run({ tenantId: 'tenant-a', userId: 'user-a', requestId: 'req-a' }, () => Promise.resolve(callback()).then(resolve, reject)));

test('SAFETY_DISPATCH accepts EMERGENCY_STOP through real DeviceControl and PLC controller', async () => { const f = productionFixture(); const result: any = await inContext(f.ctx, () => f.deviceControl.send('plc-a', { command: 'EMERGENCY_STOP', controlPath: 'SAFETY_DISPATCH', commandId: 'safety-1', payload: payload() })); assert.equal(result.status, 'SUCCEEDED'); assert.equal(f.plc.executionCount('safety-1'), 1); });
test('SAFETY_DISPATCH accepts safe PUMP_OFF', async () => { const f = productionFixture(); const result: any = await inContext(f.ctx, () => f.deviceControl.send('plc-a', { command: 'PUMP_OFF', controlPath: 'SAFETY_DISPATCH', commandId: 'safety-1', payload: payload() })); assert.equal(result.status, 'SUCCEEDED'); });
test('SAFETY_DISPATCH rejects PUMP_ON', async () => { const f = productionFixture(); await assert.rejects(() => f.deviceControl.send('plc-a', { command: 'PUMP_ON', controlPath: 'SAFETY_DISPATCH', commandId: 'safety-1', payload: payload() }), BadRequestException); assert.equal(f.plc.executionCount('safety-1'), 0); });
test('SAFETY_DISPATCH rejects VALVE_OPEN', async () => { const f = productionFixture(); await assert.rejects(() => f.deviceControl.send('plc-a', { command: 'VALVE_OPEN', controlPath: 'SAFETY_DISPATCH', commandId: 'safety-1', payload: payload() }), BadRequestException); });
for (const [name, overrides, code] of [['empty tenant', { tenantId: '' }, 'TENANT_ID_REQUIRED'], ['empty farm', { farmId: '' }, 'FARM_ID_REQUIRED'], ['invalid expiry', { expiresAt: '' }, 'EXPIRES_AT_INVALID']] as const) test(`${name} envelope fails closed`, async () => { const f = productionFixture(); const result: any = await f.plc.execute({ ...(payload(overrides) as any), action: 'EMERGENCY_STOP', parameters: {} }); assert.equal(result.errorCode, code); assert.equal(result.executed, false); });
test('invalid requestedAt fails closed', async () => { const f = productionFixture(); const result: any = await f.plc.execute({ ...(payload({ requestedAt: '' }) as any), action: 'EMERGENCY_STOP', parameters: {} }); assert.equal(result.errorCode, 'REQUESTED_AT_INVALID'); assert.equal(result.executed, false); });
test('expired E-stop dispatch is rejected independently of persistent latch', async () => { const f = productionFixture(); const result: any = await f.plc.execute({ ...(payload({ requestedAt: new Date(Date.now() - 60_000).toISOString(), expiresAt: new Date(Date.now() - 1).toISOString() }) as any), action: 'EMERGENCY_STOP', parameters: {} }); assert.equal(result.status, 'EXPIRED'); assert.equal(result.executed, false); });
test('concurrent normal and E-stop share deterministic serializer boundary', async () => { const serializer = new PriorityCommandSerializer(); const order: string[] = []; const start = serializer.submit('PUMP_ON', async () => { order.push('START'); return 1; }); const stop = serializer.submit('EMERGENCY_STOP', async () => { order.push('ESTOP'); return 1; }); await Promise.all([start, stop]); assert.deepEqual(order, ['ESTOP', 'START']); });

test('executing multi-command plan rechecks immediately before every dangerous send', async () => {
  const ctx = new RequestContextService(); let checks = 0; const sends: string[] = [];
  const plan: any = { id: 'plan', tenantId: 'tenant-a', fieldId: 'field-a', decisionId: 'decision', status: 'READY', safety: {}, decision: { farmId: 'farm-a' }, actions: [{ type: 'DEVICE_COMMAND', deviceId: 'd1', command: 'PUMP_ON' }, { type: 'DEVICE_COMMAND', deviceId: 'd2', command: 'VALVE_OPEN' }] };
  const executions: any[] = []; const prisma: any = { actionPlan: { findFirst: async () => plan, update: async ({ data }: any) => ({ ...plan, ...data, executions }) }, decisionRecord: { update: async () => ({}) }, deviceCommand: { upsert: async () => ({}), updateMany: async () => ({ count: 1 }) }, actionExecution: { findFirst: async () => null, create: async ({ data }: any) => { const row = { id: `x${executions.length}`, ...data }; executions.push(row); return row; }, update: async ({ where, data }: any) => Object.assign(executions.find((x) => x.id === where.id), data) } };
  const safety: any = { checkActionPlan: async () => ({ allowed: true, status: 'PASS', hardBlocks: [], softBlocks: [] }), assertDangerousStartAllowed: async () => { checks++; if (checks === 2) throw new Error('EMERGENCY_STOP_ACTIVE'); } };
  const executor = new ActionExecutorService(prisma, { send: async (_id: string, dto: any) => { sends.push(dto.command); return { ok: true }; } } as any, { linkActionPlanResult: async () => ({}) } as any, { create: async () => ({}) } as any, safety, ctx);
  await inContext(ctx, () => executor.executePlan('plan'));
  assert.equal(checks, 2); assert.deepEqual(sends, ['PUMP_ON']); assert.equal(executions[1].status, 'FAILED');
});

test('real SafetyService to DeviceControl path sends complete envelope', async () => { const f = productionFixture(); const logs: any[] = []; const prisma: any = { farm: { findFirst: async () => ({ id: 'farm-a' }) }, field: { findFirst: async () => ({ id: 'field-a' }) }, safetyPolicy: { findFirst: async () => null, create: async () => ({ id: 'latch-a' }) }, actionPlan: { updateMany: async () => ({ count: 0 }) }, device: { findMany: async () => [{ id: 'plc-a' }] } }; const service = new SafetyService(prisma, f.ctx, { publish: () => undefined } as any, f.deviceControl, { create: async (x: any) => { logs.push(x); return x; } } as any); const result: any = await inContext(f.ctx, () => service.emergencyStop({ farmId: 'farm-a', fieldId: 'field-a' })); assert.equal(result.dispatch, 'DISPATCHED'); assert.equal(f.plc.executionCount('emergency-stop:latch-a:plc-a'), 1); assert.equal(logs.length, 2); });

async function main() { let passed = 0; for (const item of tests) { try { await item.run(); passed++; console.log(`PASS ${item.name}`); } catch (error) { console.error(`FAIL ${item.name}`, error); process.exitCode = 1; } } console.log(`P0 SAFETY DISPATCH CLOSURE: ${passed}/${tests.length} PASS`); if (passed !== tests.length) process.exitCode = 1; }
void main();
