import 'reflect-metadata';
import assert = require('node:assert/strict');
import { ConfigService } from '@nestjs/config';
import { aggregatePhysicalStatus, resultExecutionStatus, TrustedPhysicalEvidence } from '../src/modules/execution/physical-confirmation';
import { PlcGatewayDeviceController } from '../src/modules/device-control/adapters/plc-gateway-device-controller';
import { ActionExecutorService } from '../src/modules/decision-engine/action-executor.service';
import { ExecutionResultLinkerService } from '../src/modules/execution/execution-result-linker.service';
import { RequestContextService } from '../src/common/request-context.service';
import { hasPermissions } from '../src/common/permissions/permission-matrix';
import { PERMISSIONS } from '../src/common/permissions/permission.constants';
import { PlcProfileValidator } from '../src/modules/device-control/commissioning/plc-profile.validator';

type Test = { name: string; run: () => unknown | Promise<unknown> }; const tests: Test[] = []; const test = (name: string, run: Test['run']) => tests.push({ name, run });
const baseResult = { accepted: true, transportAccepted: true, physicalConfirmed: false, executed: false, status: 'FEEDBACK_PENDING' };
test('transport accepted maps to feedback pending', () => assert.equal(resultExecutionStatus(baseResult), 'FEEDBACK_PENDING'));
test('Modbus write is not physical execution', () => assert.equal(baseResult.executed, false));
test('software ACK is not physical success', () => assert.equal(resultExecutionStatus({ ...baseResult, status: 'ACKNOWLEDGED', acknowledged: true }), 'FEEDBACK_PENDING'));
test('physical evidence maps to confirmed', () => assert.equal(resultExecutionStatus({ ...baseResult, physicalConfirmed: true }), 'PHYSICALLY_CONFIRMED'));
test('timeout remains terminal failure', () => assert.equal(resultExecutionStatus({ ...baseResult, status: 'FEEDBACK_TIMEOUT' }), 'FEEDBACK_TIMEOUT'));
test('mismatch remains terminal failure', () => assert.equal(resultExecutionStatus({ ...baseResult, status: 'FEEDBACK_MISMATCH' }), 'FEEDBACK_MISMATCH'));
test('unknown outcome remains unresolved', () => assert.equal(resultExecutionStatus({ ...baseResult, status: 'OUTCOME_UNKNOWN' }), 'OUTCOME_UNKNOWN'));
test('SENT plan awaits confirmation', () => assert.equal(aggregatePhysicalStatus([{ status: 'SENT' }]), 'AWAITING_CONFIRMATION'));
test('ACKED plan awaits confirmation', () => assert.equal(aggregatePhysicalStatus([{ status: 'ACKED' }]), 'AWAITING_CONFIRMATION'));
test('all confirmed plan completes', () => assert.equal(aggregatePhysicalStatus([{ status: 'PHYSICALLY_CONFIRMED' }, { status: 'PHYSICALLY_CONFIRMED' }]), 'CONFIRMED'));
test('one pending action keeps plan pending', () => assert.equal(aggregatePhysicalStatus([{ status: 'PHYSICALLY_CONFIRMED' }, { status: 'FEEDBACK_PENDING' }]), 'AWAITING_CONFIRMATION'));
test('feedback mismatch fails plan', () => assert.equal(aggregatePhysicalStatus([{ status: 'FEEDBACK_MISMATCH' }]), 'FAILED'));

const mapRow = (logicalName:string,type:string,address:number,readWrite:'R'|'W',feedbackPoint?:string,overrides:Record<string,unknown>={}) => ({ logicalName,type,functionCode:type,address,dataType:'boolean',scale:1,unit:'state',readWrite,feedbackPoint,timeoutMs:100,retry:0,failSafeState:'OFF',...overrides });
const profileDocument = (mapping:any[], overrides:Record<string,unknown>={}) => ({ profileVersion:'1',vendor:'TEST',family:'TEST',model:'FAKE',partNumber:'TEST',hardwareVersion:'TEST',firmwareVersion:'TEST',testOnly:true,realHardwareApproved:false,transport:{type:'MODBUS_TCP',host:'127.0.0.1',port:1502,unitId:1},source:{manualName:'TEST',manualVersion:'TEST',manualUrlOrReference:'TEST',verifiedBy:'TEST',verifiedAt:new Date().toISOString()},mapping,...overrides });
const valveRows = () => [mapRow('valveOpen','coil',10,'W','valveOpenFeedback'),mapRow('valveOpenFeedback','discreteInput',20,'R')];
test('command row before feedback row resolves feedback input', () => { const profile:any=profileDocument(valveRows()); const f=controllerFixture({PLC_PROFILE:profile}); assert.equal((f.controller as any).feedbackPoint(profile,'valveOpenFeedback').address,20); });
test('feedback row before command row resolves same feedback input', () => { const rows=valveRows().reverse(); const profile:any=profileDocument(rows); const f=controllerFixture({PLC_PROFILE:profile}); assert.equal((f.controller as any).feedbackPoint(profile,'valveOpenFeedback').address,20); });
test('valve output coil cannot self-confirm valve feedback', () => { const profile:any=profileDocument(valveRows()); const f=controllerFixture({PLC_PROFILE:profile}); assert.notEqual((f.controller as any).feedbackPoint(profile,'valveOpenFeedback').address,10); });
test('pump output cannot self-confirm pump feedback', () => { const rows=[mapRow('pumpStart','coil',11,'W','pumpRunningFeedback'),mapRow('pumpRunningFeedback','discreteInput',21,'R')]; const profile:any=profileDocument(rows); const f=controllerFixture({PLC_PROFILE:profile}); assert.equal((f.controller as any).feedbackPoint(profile,'pumpRunningFeedback').address,21); });
test('missing referenced feedback mapping invalidates profile', () => { const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument([mapRow('valveOpen','coil',10,'W','valveOpenFeedback')]))); assert.equal(result.schemaValid,false); assert(result.errors.some((x)=>x.includes('feedbackPoint_NOT_FOUND'))); });
test('nonexistent feedback logicalName invalidates profile', () => { const rows=[mapRow('valveOpen','coil',10,'W','doesNotExist')]; const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument(rows))); assert(result.errors.some((x)=>x.includes('feedbackPoint_NOT_FOUND'))); });
test('WRITE-only referenced feedback row invalidates profile', () => { const rows=[mapRow('valveOpen','coil',10,'W','valveOpenFeedback'),mapRow('valveOpenFeedback','coil',20,'W','valveOpenFeedback')]; const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument(rows))); assert(result.errors.some((x)=>x.includes('NOT_READ_CAPABLE'))); });
test('unconfirmed feedback mapping invalidates profile', () => { const rows=[mapRow('valveOpen','coil',10,'W','valveOpenFeedback'),mapRow('valveOpenFeedback','discreteInput',20,'R',undefined,{functionCode:'UNCONFIRMED'})]; const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument(rows))); assert.equal(result.schemaValid,false); });
test('unsupported feedback function invalidates profile', () => { const rows=[mapRow('valveOpen','coil',10,'W','valveOpenFeedback'),mapRow('valveOpenFeedback','vendorMagic',20,'R')]; const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument(rows))); assert(result.errors.some((x)=>x.includes('FUNCTION_UNSUPPORTED'))); });
test('explicit snake_case alias resolves deterministically and remains testOnly', () => { const rows=[mapRow('valve_open','coil',10,'W','valve_open_feedback'),mapRow('valve_open_feedback','discreteInput',20,'R')]; const result=new PlcProfileValidator().validate(JSON.stringify(profileDocument(rows))); assert.equal(result.schemaValid,true); assert.equal(result.realProfileValid,false); });

function controllerFixture(overrides: Record<string, unknown> = {}) {
  const state = new Map<number, boolean>([[1, false], [2, false], [3, false], [4, false], [5, true], [6, false]]); let writes = 0; let reads = 0;
  const transport: any = { healthCheck: async () => ({ connected: true }), readDiscreteInput: async (address: number) => { reads++; return state.get(address) ?? false; }, readCoil: async (address: number) => { reads++; return state.get(address) ?? false; }, readHoldingRegister: async () => 0, readInputRegister: async () => 0, writeCoil: async (address: number) => { writes++; if (address === 10) state.set(4, true); if (address === 11) state.set(4, false); if (address === 12) { state.set(5, true); state.set(6, false); } if (address === 13) { state.set(5, false); state.set(6, true); } }, writeHoldingRegister: async () => undefined };
  const values: Record<string, unknown> = { NODE_ENV: 'test', DEVICE_CONTROL_MODE: 'PLC_GATEWAY', DEVICE_CONTROL_DRY_RUN: 'false', VALVE_ALLOW_REAL_CONTROL: 'true', ENABLE_AUTO_EXECUTION: 'true', PLC_TRANSPORT: 'MODBUS_TCP', PLC_REAL_WRITE_ENABLED: 'true', PLC_FEEDBACK_TIMEOUT_MS: '15', PLC_FEEDBACK_POLL_INTERVAL_MS: '1', PLC_FEEDBACK_MAX_AGE_MS: '50', PLC_PROFILE: { testOnly: true, unitId: 1, points: { emergencyStop: { type: 'discreteInput', address: 1 }, noWater: { type: 'discreteInput', address: 2 }, overloadTrip: { type: 'discreteInput', address: 3 }, pumpRunningFeedback: { type: 'discreteInput', address: 4 }, valveOpenFeedback: { type: 'discreteInput', address: 5 }, valveCloseFeedback: { type: 'discreteInput', address: 6 }, pumpStart: { type: 'coil', address: 10 }, pumpStop: { type: 'coil', address: 11 }, valveOpen: { type: 'coil', address: 12 }, valveClose: { type: 'coil', address: 13 } } }, ...overrides };
  return { controller: new PlcGatewayDeviceController({ get: (key: string) => values[key] } as ConfigService, transport), state, reads: () => reads, writes: () => writes };
}
let commandSequence = 0; const command = (action: any) => { const id = `physical-${++commandSequence}`; return { commandId: id, idempotencyKey: id, tenantId: 'tenant-a', farmId: 'farm-a', deviceId: 'plc-a', action, requestedAt: new Date().toISOString(), expiresAt: new Date(Date.now() + 1000).toISOString(), parameters: {} }; };
test('read-only Modbus status reads confirmed profile points', async () => { const f = controllerFixture({ PLC_REAL_WRITE_ENABLED: 'false' }); const status = await f.controller.readStatus('plc-a'); assert.equal(status.online, true); assert.equal(f.reads(), 5); assert.equal(f.writes(), 0); });
test('read-only status remains available with real writes disabled', async () => { const f = controllerFixture({ PLC_REAL_WRITE_ENABLED: 'false' }); assert.equal((await f.controller.readStatus('plc-a')).source, 'MODBUS_TCP'); });
test('missing feedback profile fails closed', async () => { const f = controllerFixture({ PLC_PROFILE: { testOnly: true, unitId: 1, points: { pumpStart: { type: 'coil', address: 10 } } } }); assert.equal((await f.controller.readStatus('plc-a')).errorCode, 'FEEDBACK_UNAVAILABLE'); });
test('valve confirmation permits pump start', async () => { const f = controllerFixture(); const result = await f.controller.execute(command('PUMP_ON') as any); assert.equal(result.status, 'PHYSICALLY_CONFIRMED'); assert.equal(result.physicalConfirmed, true); });
test('valve open is pending until feedback path confirms', async () => { const f = controllerFixture(); f.state.set(5, false); const result = await f.controller.execute(command('VALVE_OPEN') as any); assert.equal(result.status, 'PHYSICALLY_CONFIRMED'); assert.equal(result.feedback?.logicalPoint, 'valveOpenFeedback'); });
test('backend valve open remains blocked during emergency stop', async () => { const f = controllerFixture(); f.state.set(1, true); const result = await f.controller.execute(command('VALVE_OPEN') as any); assert.equal(result.errorCode, 'EMERGENCY_STOP_ACTIVE'); assert.equal(f.writes(), 0); });
test('pump start blocked without valve feedback', async () => { const f = controllerFixture(); f.state.set(5, false); const result = await f.controller.execute(command('PUMP_ON') as any); assert.equal(result.errorCode, 'PUMP_INTERLOCK_BLOCKED'); assert.equal(f.writes(), 0); });
test('pump stop waits for stopped feedback', async () => { const f = controllerFixture(); f.state.set(4, true); const result = await f.controller.execute(command('PUMP_OFF') as any); assert.equal(result.status, 'PHYSICALLY_CONFIRMED'); });
test('valve close blocked while pump-running feedback is true', async () => { const f = controllerFixture(); f.state.set(4, true); const result = await f.controller.execute(command('VALVE_CLOSE') as any); assert.equal(result.errorCode, 'STOP_PUMP_BEFORE_VALVE_CLOSE'); assert.equal(f.writes(), 0); });
test('valve close allowed after pump-stopped feedback', async () => { const f = controllerFixture(); f.state.set(4, false); const result = await f.controller.execute(command('VALVE_CLOSE') as any); assert.equal(result.status, 'PHYSICALLY_CONFIRMED'); });
test('E-stop latch dispatch does not claim confirmation before feedback', async () => { const f = controllerFixture(); f.state.set(4, true); const transport: any = (f.controller as any).modbusTransport; transport.writeCoil = async () => undefined; const result = await f.controller.execute(command('EMERGENCY_STOP') as any); assert.equal(result.status, 'FEEDBACK_TIMEOUT'); assert.equal(result.physicalConfirmed, false); });
test('E-stop physical stop confirms only after stopped feedback', async () => { const f = controllerFixture(); f.state.set(4, true); const result = await f.controller.execute(command('EMERGENCY_STOP') as any); assert.equal(result.status, 'PHYSICALLY_CONFIRMED'); });
test('contradictory valve feedback is mismatch', async () => { const f = controllerFixture(); f.state.set(5, false); f.state.set(6, true); (f.controller as any).modbusTransport.writeCoil = async () => undefined; const result = await f.controller.execute(command('VALVE_OPEN') as any); assert.equal(result.status, 'FEEDBACK_MISMATCH'); });
test('feedback timeout never confirms', async () => { const f = controllerFixture(); f.state.set(4, true); (f as any).controller['modbusTransport'].writeCoil = async () => undefined; const result = await f.controller.execute(command('PUMP_OFF') as any); assert.equal(result.status, 'FEEDBACK_TIMEOUT'); assert.equal(result.physicalConfirmed, false); });
test('stale in-memory status blocks dangerous start', async () => { const f = controllerFixture(); (f.controller as any).readStatus = async () => ({ online: true, emergencyStop: false, noWater: false, overloadTrip: false, pumpRunning: false, valveOpen: true, observedAt: new Date(0).toISOString(), source: 'MEMORY', fresh: false, stale: true }); const result = await f.controller.execute(command('PUMP_ON') as any); assert.equal(result.errorCode, 'STALE_PLC_STATUS'); assert.equal(f.writes(), 0); });
test('duplicate command has one physical write', async () => { const f = controllerFixture(); const c = command('PUMP_ON'); await f.controller.execute(c as any); await f.controller.execute(c as any); assert.equal(f.writes(), 1); });

function linkerFixture(status: string) {
  const effects = { tank: 0, usage: 0, activity: 0, report: 0, finished: 0 };
  const plan: any = { id: 'plan', status: status === 'FAILED' ? 'FAILED' : 'AWAITING_CONFIRMATION', fieldId: 'field', actions: [{ payload: { targetFertilizerVolume: 5 } }], executions: [{ status }], decision: {} };
  let completionClaimed = false;
  const prisma: any = { actionPlan: { findUnique: async () => plan }, irrigationRotationRun: { findFirst: async () => null }, fertigationTask: { findFirst: async () => ({ id: 'task', tenantId: 'tenant-a', farmId: 'farm', fieldId: 'field', tankId: 'tank', targetFertilizerVolume: 5, resultJson: {} }), findUnique: async () => ({ id: 'task', status: 'SUCCESS' }), updateMany: async () => { if (completionClaimed) return { count: 0 }; completionClaimed = true; return { count: 1 }; }, update: async ({ data }: any) => { if (data.finishedAt) effects.finished++; return data; } }, dissolveFertilizerTask: { findUnique: async () => null }, fertilizerTank: { findUnique: async () => ({ id: 'tank', currentLevelL: 50 }), update: async () => { effects.tank++; } }, operationReport: { findFirst: async () => effects.report ? ({ id: 'report' }) : null, create: async () => { effects.report++; }, update: async () => ({}) }, farmActivity: { findFirst: async () => effects.activity ? ({ id: 'activity' }) : null, create: async () => { effects.activity++; } }, usageRecord: { findFirst: async () => effects.usage ? ({ id: 'usage' }) : null, create: async () => { effects.usage++; } } };
  return { linker: new ExecutionResultLinkerService(prisma, { publish: () => undefined } as any), effects, plan };
}
test('transport-only fertigation has no business completion', async () => { const f = linkerFixture('SENT'); const result: any = await f.linker.linkActionPlanResult('plan'); assert.equal(result.status, 'AWAITING_CONFIRMATION'); assert.deepEqual(f.effects, { tank: 0, usage: 0, activity: 0, report: 0, finished: 0 }); });
test('ACK-only fertigation has no inventory decrement', async () => { const f = linkerFixture('ACKED'); await f.linker.linkActionPlanResult('plan'); assert.equal(f.effects.tank, 0); });
test('confirmed fertigation completes business once', async () => { const f = linkerFixture('PHYSICALLY_CONFIRMED'); f.plan.status = 'EXECUTED'; await f.linker.linkActionPlanResult('plan'); assert.deepEqual(f.effects, { tank: 1, usage: 1, activity: 1, report: 1, finished: 1 }); });
test('duplicate confirmation does not double business effects', async () => { const f = linkerFixture('PHYSICALLY_CONFIRMED'); f.plan.status = 'EXECUTED'; let taskResult: any = {}; const prisma: any = (f as any).linker['prisma']; prisma.fertigationTask.findFirst = async () => ({ id: 'task', tenantId: 'tenant-a', farmId: 'farm', fieldId: 'field', tankId: 'tank', targetFertilizerVolume: 5, resultJson: taskResult }); prisma.fertigationTask.update = async ({ data }: any) => { taskResult = data.resultJson; if (data.finishedAt && !f.effects.finished) f.effects.finished++; return data; }; await f.linker.linkActionPlanResult('plan'); await f.linker.linkActionPlanResult('plan'); assert.deepEqual(f.effects, { tank: 1, usage: 1, activity: 1, report: 1, finished: 1 }); });

function feedbackFixture(executionStatus = 'FEEDBACK_PENDING') {
  const ctx = new RequestContextService(); const execution: any = { id: 'execution', tenantId: 'tenant-a', actionPlanId: 'plan', requestId: 'command-a', deviceId: 'device-a', status: executionStatus };
  execution.result = { identity: { tenantId: 'tenant-a', farmId: 'farm-a', deviceId: 'device-a', commandId: 'command-a' } };
  const prisma: any = { actionExecution: { findFirst: async () => execution, findUnique: async () => ({ actionPlanId: 'plan' }), update: async ({ data }: any) => Object.assign(execution, data), findMany: async () => [execution] }, deviceCommand: { findMany: async () => [], updateMany: async () => ({ count: 1 }) }, actionPlan: { update: async () => ({ decisionId: 'decision' }) }, decisionRecord: { update: async () => ({}) }, actionQueueJob: { updateMany: async () => ({ count: 1 }) } };
  const service = new ActionExecutorService(prisma, {} as any, { linkActionPlanResult: async () => ({}) } as any, { create: async () => ({}) } as any, {} as any, ctx);
  const run = <T>(fn: () => Promise<T>) => new Promise<T>((resolve, reject) => ctx.run({ tenantId: 'tenant-a', userId: 'user-a' }, () => fn().then(resolve, reject)));
  return { service, execution, run };
}
const validFeedback = { status: 'PHYSICALLY_CONFIRMED' as const, payload: { tenantId: 'tenant-a', farmId: 'farm-a', deviceId: 'device-a', commandId: 'command-a', physicalConfirmed: true, source: 'MODBUS_TCP', observedAt: new Date().toISOString(), expectedState: true, observedState: true } };
const trusted = (overrides: Record<string,unknown>={}) => TrustedPhysicalEvidence.fromPlcReadback({ ...validFeedback, payload: { ...validFeedback.payload, ...overrides } });
test('human diagnostic feedback does not change authoritative state', async () => { const f = feedbackFixture(); await f.run(() => f.service.feedback('execution', { status: 'ACKED', message: 'manual note' })); assert.equal(f.execution.status, 'FEEDBACK_PENDING'); });
test('INSTALLER with EDGE_MANAGE cannot forge physical confirmation', async () => { assert.equal(hasPermissions('INSTALLER', [PERMISSIONS.EDGE_MANAGE]), true); const f = feedbackFixture(); await assert.rejects(() => f.run(() => f.service.feedback('execution', validFeedback)), /HUMAN_PHYSICAL_CONFIRMATION_FORBIDDEN/); assert.equal(f.execution.status, 'FEEDBACK_PENDING'); });
test('string-only MODBUS source is not trusted evidence', async () => { const f = feedbackFixture(); await assert.rejects(() => f.service.applyTrustedPhysicalFeedback('execution', validFeedback as any), /TRUSTED_MACHINE_EVIDENCE_REQUIRED/); assert.equal(f.execution.status, 'FEEDBACK_PENDING'); });
test('wrong tenant feedback rejected', async () => { const f = feedbackFixture(); await assert.rejects(() => f.service.applyTrustedPhysicalFeedback('execution', trusted({tenantId:'other'})), /FEEDBACK_IDENTITY_MISMATCH/); });
test('wrong device feedback rejected', async () => { const f = feedbackFixture(); await assert.rejects(() => f.service.applyTrustedPhysicalFeedback('execution', trusted({deviceId:'other'})), /FEEDBACK_IDENTITY_MISMATCH/); });
test('wrong command feedback rejected', async () => { const f = feedbackFixture(); await assert.rejects(() => f.service.applyTrustedPhysicalFeedback('execution', trusted({commandId:'other'})), /FEEDBACK_IDENTITY_MISMATCH/); });
test('wrong farm feedback rejected', async () => { const f = feedbackFixture(); await assert.rejects(() => f.service.applyTrustedPhysicalFeedback('execution', trusted({farmId:'other'})), /FEEDBACK_IDENTITY_MISMATCH/); });
test('physical confirmation without evidence rejected', () => { assert.throws(() => TrustedPhysicalEvidence.fromPlcReadback({ status:'PHYSICALLY_CONFIRMED', payload: { tenantId:'tenant-a' } }), /INVALID_TRUSTED_PLC_EVIDENCE/); });
test('duplicate matching terminal feedback is idempotent', async () => { const f = feedbackFixture('PHYSICALLY_CONFIRMED'); const before = { ...f.execution }; await f.service.applyTrustedPhysicalFeedback('execution', trusted()); assert.deepEqual(f.execution, before); });
test('five duplicate confirmations remain one terminal state', async () => { const f = feedbackFixture('PHYSICALLY_CONFIRMED'); for (let index = 0; index < 5; index++) await f.service.applyTrustedPhysicalFeedback('execution', trusted()); assert.equal(f.execution.status, 'PHYSICALLY_CONFIRMED'); });
test('ten duplicate confirmations remain one terminal state', async () => { const f = feedbackFixture('PHYSICALLY_CONFIRMED'); for (let index = 0; index < 10; index++) await f.service.applyTrustedPhysicalFeedback('execution', trusted()); assert.equal(f.execution.status, 'PHYSICALLY_CONFIRMED'); });
test('late feedback does not resurrect timeout', async () => { const f = feedbackFixture('FEEDBACK_TIMEOUT'); await f.service.applyTrustedPhysicalFeedback('execution', trusted()); assert.equal(f.execution.status, 'FEEDBACK_TIMEOUT'); });
test('production PLC readback creates trusted internal physical confirmation', async () => { const plc=controllerFixture(); const result:any=await plc.controller.execute({ ...command('PUMP_ON'), commandId:'command-a', idempotencyKey:'command-a', tenantId:'tenant-a', farmId:'farm-a', deviceId:'device-a' } as any); assert.equal(result.status,'PHYSICALLY_CONFIRMED'); const f=feedbackFixture(); const evidence=TrustedPhysicalEvidence.fromPlcReadback({status:'PHYSICALLY_CONFIRMED',payload:result.feedback}); await f.service.applyTrustedPhysicalFeedback('execution',evidence); assert.equal(f.execution.status,'PHYSICALLY_CONFIRMED'); });

test('restart marks DISPATCHING outcome unknown without resend', async () => { const f = feedbackFixture('DISPATCHING'); let sends = 0; (f.service as any).deviceControlService = { send: async () => { sends++; } }; const count = await f.service.reconcileInterruptedDispatches(); assert.equal(count, 1); assert.equal(f.execution.status, 'OUTCOME_UNKNOWN'); assert.equal(sends, 0); });
test('restart marks orphaned pre-send claim unknown without resend', async () => { const f = feedbackFixture('PENDING'); const prisma:any=(f.service as any).prisma; prisma.actionExecution.findMany=async()=>[]; let status='DISPATCHING'; prisma.deviceCommand.findMany=async()=>[{requestId:'orphan',status}]; prisma.deviceCommand.updateMany=async({data}:any)=>{status=data.status;return{count:1}}; let sends=0;(f.service as any).deviceControlService={send:async()=>{sends++;}};assert.equal(await f.service.reconcileInterruptedDispatches(),1);assert.equal(status,'OUTCOME_UNKNOWN');assert.equal(sends,0);});

async function main() { let passed = 0; for (const item of tests) { try { await item.run(); passed++; console.log(`PASS ${item.name}`); } catch (error) { console.error(`FAIL ${item.name}`, error); process.exitCode = 1; } } console.log(`P0 PHYSICAL CONFIRMATION: ${passed}/${tests.length} PASS`); if (passed !== tests.length) process.exitCode = 1; }
void main();
