ALTER TABLE `CostRecord` ADD COLUMN `sourceType` VARCHAR(191) NULL;
ALTER TABLE `CostRecord` ADD COLUMN `sourceId` VARCHAR(191) NULL;
ALTER TABLE `CostRecord` ADD COLUMN `isReversed` BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE `CostRecord` ADD COLUMN `reversedAt` DATETIME(3) NULL;
ALTER TABLE `CostRecord` ADD COLUMN `reverseReason` TEXT NULL;

ALTER TABLE `IrrigationRecord` MODIFY `mode` ENUM('MANUAL', 'AUTO', 'SCHEDULED', 'ADVICE_EXECUTED') NOT NULL;
