ALTER TABLE `DeviceCommand`
  MODIFY `status` ENUM(
    'PENDING', 'DISPATCHING', 'SENT', 'ACKED', 'FEEDBACK_PENDING',
    'PHYSICALLY_CONFIRMED', 'FEEDBACK_MISMATCH', 'FEEDBACK_TIMEOUT',
    'FEEDBACK_UNAVAILABLE', 'OUTCOME_UNKNOWN', 'FAILED', 'TIMEOUT'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `DecisionRecord`
  MODIFY `status` ENUM(
    'PROPOSED', 'PLANNED', 'AWAITING_CONFIRMATION', 'EXECUTED', 'SKIPPED', 'FAILED'
  ) NOT NULL DEFAULT 'PROPOSED';

ALTER TABLE `ActionPlan`
  MODIFY `status` ENUM(
    'PLANNED', 'PENDING_APPROVAL', 'BLOCKED', 'EXECUTING',
    'AWAITING_CONFIRMATION', 'EXECUTED', 'SKIPPED', 'FAILED'
  ) NOT NULL DEFAULT 'PLANNED';

ALTER TABLE `ActionExecution`
  MODIFY `status` ENUM(
    'PENDING', 'DISPATCHING', 'SENT', 'ACKED', 'FEEDBACK_PENDING',
    'PHYSICALLY_CONFIRMED', 'FEEDBACK_MISMATCH', 'FEEDBACK_TIMEOUT',
    'FEEDBACK_UNAVAILABLE', 'OUTCOME_UNKNOWN', 'FAILED', 'SKIPPED'
  ) NOT NULL DEFAULT 'PENDING';

ALTER TABLE `ActionQueueJob`
  MODIFY `status` ENUM(
    'PENDING', 'QUEUED', 'EXECUTING', 'AWAITING_CONFIRMATION',
    'SUCCESS', 'FAILED', 'RETRYING', 'DEAD_LETTERED'
  ) NOT NULL DEFAULT 'PENDING';
