ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'DISPATCHING';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_PENDING';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'PHYSICALLY_CONFIRMED';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_MISMATCH';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_TIMEOUT';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_UNAVAILABLE';
ALTER TYPE "DeviceCommandStatus" ADD VALUE IF NOT EXISTS 'OUTCOME_UNKNOWN';

ALTER TYPE "DecisionStatus" ADD VALUE IF NOT EXISTS 'AWAITING_CONFIRMATION';
ALTER TYPE "ActionPlanStatus" ADD VALUE IF NOT EXISTS 'AWAITING_CONFIRMATION';

ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'DISPATCHING';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_PENDING';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'PHYSICALLY_CONFIRMED';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_MISMATCH';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_TIMEOUT';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'FEEDBACK_UNAVAILABLE';
ALTER TYPE "ActionExecutionStatus" ADD VALUE IF NOT EXISTS 'OUTCOME_UNKNOWN';

ALTER TYPE "ActionQueueJobStatus" ADD VALUE IF NOT EXISTS 'AWAITING_CONFIRMATION';
