import { strict as assert } from 'node:assert';
import test from 'node:test';
import { PlcTransportPort } from '@agrios/edge-core';
import { EdgeConfig } from '../config';
import { EdgeDeviceControl } from '../device-control';

const profile = { realHardwareApproved: true, testOnly: false, mapping: [
  ['emergencyStop', 'discreteInput', 1], ['noWater', 'discreteInput', 2], ['overloadTrip', 'discreteInput', 3], ['pumpRunningFeedback', 'discreteInput', 4], ['valveOpenFeedback', 'discreteInput', 5], ['valveCloseFeedback', 'discreteInput', 6],
  ['pumpStart', 'coil', 10], ['pumpStop', 'coil', 11], ['valveOpen', 'coil', 12], ['valveClose', 'coil', 13]
].map(([logicalName,type,address])=>({logicalName,type,address,functionCode:type,feedbackPoint:logicalName})) };
class LocalTransport implements PlcTransportPort { state=new Map<number,boolean>([[1,false],[2,false],[3,false],[4,false],[5,true],[6,false]]); writes=0; update=true; async connect(){} async disconnect(){} async healthCheck(){return{connected:true,transport:'LOCAL_TEST'}} async readCoil(a:number){return this.state.get(a)??false} async readDiscreteInput(a:number){return this.state.get(a)??false} async readHoldingRegister(){return 0} async readInputRegister(){return 0} async writeCoil(a:number){this.writes++;if(this.update){if(a===10)this.state.set(4,true);if(a===11)this.state.set(4,false);if(a===12){this.state.set(5,true);this.state.set(6,false)}if(a===13){this.state.set(5,false);this.state.set(6,true)}}} async writeHoldingRegister(){} async transaction<T>(op:()=>Promise<T>){return op()} }
const config = (transport:'FAKE'|'MODBUS_TCP'):EdgeConfig => ({ edgeId:'edge',tenantId:'tenant',farmId:'farm',allowedDeviceIds:['plc'],softwareVersion:'test',configVersion:'test',mqtt:{host:'localhost',port:1883,tls:false,clientId:'test',hmacKeyPath:'test',telemetryTopic:'',commandsTopic:'',acksTopic:'',healthTopic:''},storage:{path:'test',maxQueueSize:10,maxStorageBytes:10000,retentionMs:1000},reconnect:{initialDelayMs:1,maxDelayMs:10,jitter:0},plc:{transport,host:'127.0.0.1',port:1502,profilePath:'test',realProfileApproved:true},safety:{realWriteEnabled:true,feedbackTimeoutMs:5,feedbackPollIntervalMs:1},healthIntervalMs:100});
const gates = ['DEVICE_CONTROL_MODE','DEVICE_CONTROL_DRY_RUN','VALVE_ALLOW_REAL_CONTROL','ENABLE_AUTO_EXECUTION','PLC_TRANSPORT','PLC_REAL_WRITE_ENABLED'] as const;
function enableGates(){const previous=Object.fromEntries(gates.map((key)=>[key,process.env[key]]));Object.assign(process.env,{DEVICE_CONTROL_MODE:'PLC_GATEWAY',DEVICE_CONTROL_DRY_RUN:'false',VALVE_ALLOW_REAL_CONTROL:'true',ENABLE_AUTO_EXECUTION:'true',PLC_TRANSPORT:'MODBUS_TCP',PLC_REAL_WRITE_ENABLED:'true'});return()=>{for(const key of gates)previous[key]===undefined?delete process.env[key]:process.env[key]=previous[key];};}

test('Edge real transport success without feedback times out and never claims physical success', async()=>{const restore=enableGates();try{const transport=new LocalTransport();transport.update=false;transport.state.set(4,true);const control=new EdgeDeviceControl(config('MODBUS_TCP'),transport,true,async()=>undefined,profile);const result:any=await control.execute({commandId:'stop',action:'PUMP_OFF'});assert.equal(result.status,'FEEDBACK_TIMEOUT');assert.equal(result.physicalConfirmed,false);}finally{restore();}});
test('Edge pump start requires valve feedback then confirms pump feedback', async()=>{const restore=enableGates();try{const transport=new LocalTransport();transport.state.set(5,false);const control=new EdgeDeviceControl(config('MODBUS_TCP'),transport,true,async()=>undefined,profile);const blocked:any=await control.execute({commandId:'blocked',action:'PUMP_ON'});assert.equal(blocked.errorCode,'PUMP_INTERLOCK_BLOCKED');transport.state.set(5,true);const confirmed:any=await control.execute({commandId:'confirmed',action:'PUMP_ON'});assert.equal(confirmed.status,'PHYSICALLY_CONFIRMED');assert.equal(transport.writes,1);}finally{restore();}});
test('Edge valve close remains blocked until pump stopped', async()=>{const restore=enableGates();try{const transport=new LocalTransport();transport.state.set(4,true);const control=new EdgeDeviceControl(config('MODBUS_TCP'),transport,true,async()=>undefined,profile);const result:any=await control.execute({commandId:'close',action:'VALVE_CLOSE'});assert.equal(result.errorCode,'STOP_PUMP_BEFORE_VALVE_CLOSE');assert.equal(transport.writes,0);}finally{restore();}});
test('Edge valve open is blocked during emergency stop', async()=>{const restore=enableGates();try{const transport=new LocalTransport();transport.state.set(1,true);const control=new EdgeDeviceControl(config('MODBUS_TCP'),transport,true,async()=>undefined,profile);const result:any=await control.execute({commandId:'open',action:'VALVE_OPEN'});assert.equal(result.errorCode,'EMERGENCY_STOP_ACTIVE');assert.equal(transport.writes,0);}finally{restore();}});
test('Edge fake feedback is explicitly test-only', async()=>{const transport=new LocalTransport();const control=new EdgeDeviceControl(config('FAKE'),transport,false,async()=>undefined);const result:any=await control.execute({commandId:'fake',action:'PUMP_OFF'});assert.equal(result.physicalConfirmed,true);assert.equal(result.feedback.fake,true);});
