persistence true
persistence_location /mosquitto/data/
autosave_interval 60

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

per_listener_settings true
listener 8883
protocol mqtt
allow_anonymous false

certfile /mosquitto/secrets/tls/fullchain.pem
keyfile /mosquitto/secrets/tls/privkey.pem
tls_version tlsv1.2
require_certificate false

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/secrets/dynamic-security.json

max_packet_size 65536
max_queued_messages 1000
max_queued_bytes 67108864
max_inflight_messages 20
max_keepalive 300
